/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Aplicacion;
import Clases.GrupoListas;
import Clases.ListaCliente;
import Clases.ListaMenu;
import Clases.ListaPedidos;
import Clases.ListaRestaurant;
import Clases.ListaRutas;
import Clases.NodoPlato;
import Clases.NodoRestaurant;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Jose
 */
public class VentanaEliminarPlato extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEliminarPlato
     */
    GrupoListas grupo_listas = Aplicacion.getGrupoListas();
    ListaPedidos pedidos = grupo_listas.getPedidos();
    ListaRestaurant restaurantes = grupo_listas.getRestaurantes();
    ListaCliente clientes = grupo_listas.getClientes();
    ListaRutas rutas = grupo_listas.getRutas();
    
    public VentanaEliminarPlato() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        restaurantComboBox = new javax.swing.JComboBox<>();
        platoComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Samancito Delivery");

        jLabel1.setText("ELIMINAR PLATO");

        jLabel2.setText("Producto a eliminar:");

        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Restaurante:");

        restaurantComboBox.setModel(new javax.swing.DefaultComboBoxModel<NodoRestaurant>(getRestaurantComboBoxModel()));
        restaurantComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                restaurantComboBoxItemStateChanged(evt);
            }
        });

        platoComboBox.setModel(new javax.swing.DefaultComboBoxModel<NodoPlato>(getPlatoComboBoxModel(restaurantes.getPrimero().getMenu())));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(platoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(restaurantComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(platoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(BotonEliminar)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        // TODO add your handling code here:
        try{
            NodoRestaurant restaurant = (NodoRestaurant) restaurantComboBox.getSelectedItem();
            ListaMenu menu = restaurant.getMenu();
            NodoPlato plato_eliminar = (NodoPlato) platoComboBox.getSelectedItem();
            menu.eliminarPlato(plato_eliminar);
            JOptionPane.showMessageDialog(this, "Producto eliminado con exito");
            dispose();
        }catch(Exception er){
            JOptionPane.showMessageDialog(this, "Por favor ingrese valores validos");
        }
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void restaurantComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_restaurantComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            NodoRestaurant restaurant = (NodoRestaurant) evt.getItem();
            platoComboBox.setModel(new DefaultComboBoxModel<>(getPlatoComboBoxModel(restaurant.getMenu())));
        }
    }//GEN-LAST:event_restaurantComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEliminarPlato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<NodoPlato> platoComboBox;
    private javax.swing.JComboBox<NodoRestaurant> restaurantComboBox;
    // End of variables declaration//GEN-END:variables

    private NodoRestaurant[] getRestaurantComboBoxModel() {
        NodoRestaurant[] restaurants = new NodoRestaurant[restaurantes.getTamano()];
        if (!restaurantes.esta_vacia()) {
            NodoRestaurant temp = restaurantes.getPrimero();
            for (int i = 0; temp != null; i++, temp = temp.getSiguiente()) {
                restaurants[i] = temp;
            }
        }
        
        return restaurants;
    }

    private NodoPlato[] getPlatoComboBoxModel(ListaMenu menu) {
        NodoPlato[] platos = new NodoPlato[menu.getTamano()];
        if (!menu.esta_vacia()) {
            NodoPlato temp = menu.getPrimero();
            for (int i = 0; temp != null; i++, temp = temp.getSiguiente()) {
                platos[i] = temp;
            }
        }
        
        return platos;
    }
}
